django:
  build: .
  command: ["./wait-for-it.sh", "mysql:3306", "--", "bash", "run.sh"]
  links:
    - mysql:mysql
    - redis:redis
mysql:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: 'django'
    MYSQL_PASSWORD: 'mysql'
    MYSQL_ROOT_PASSWORD: 'mysql'
redis:
  image: redis:latest
