django:
  build: .
  command: python manage.py runserver 0.0.0.0:8080
#  ports:
#    - "8080:8080"
  links:
    - mysql:mysql
    - redis:redis
mysql:
  image: mysql:5.7
#  ports:
#    - "3306:3306"
  environment:
    MYSQL_DATABASE: 'django'
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: 'mysql'
    MYSQL_ROOT_PASSWORD: 'mysql'
redis:
  image: redis:latest
