# Generated by Django 2.0 on 2020-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField(max_length=100)),
            ],
            options={
                'verbose_name': 'game',
                'ordering': ['gameID'],
            },
        ),
    ]
