# Generated by Django 2.2.11 on 2020-03-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomName',
            new_name='name',
        ),
    ]
