# Generated by Django 2.2.11 on 2020-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200325_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='nbUser',
            field=models.IntegerField(default=0),
        ),
    ]
