# Generated by Django 2.2.11 on 2020-03-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200325_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='nbUser',
            new_name='nbUsers',
        ),
    ]
